In [2]:
import torch

#### autograd

In [8]:
x = torch.randn(3, requires_grad=True)
x

tensor([ 0.7624,  0.7127, -0.9167], requires_grad=True)

In [10]:
y = x+2
z = y*y*2
z = z.mean()

In [11]:
z

tensor(10.7753, grad_fn=<MeanBackward0>)

In [12]:
z.backward()

In [13]:
x.grad

tensor([3.6832, 3.6169, 1.4444])

- Grad accumulates
- Whenever we want to calculate the gradients requires_grad must be set to True

In [18]:
weights = torch.ones(4, requires_grad=True)

for epoch in range(4):
    model_output = (weights*3).sum()
    
    model_output.backward()
    
    print(weights.grad)
    
    weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


## Backpropagation 

In [24]:
x = torch.tensor(1.0)
y = torch.tensor(2.0)


w = torch.tensor(1.0, requires_grad=True)


# forward pass and compute the loss

y_hat = w * x
loss = (y_hat - y)**2

print(loss)

# backward pass

loss.backward()
print(w.grad)


# update weights
# next forward

tensor(1., grad_fn=<PowBackward0>)
tensor(-2.)
